spring:
  application:
    name: weather-information-service
  datasource: 
    url: jdbc:mysql://localhost:3306/elli_mae
    password: root
    username: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
server:
  port: 8089
  